kind: Deployment
apiVersion: apps/v1
metadata:
  name: tis-gf-auth
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ishankhare07/ingress-test:0.0.3
        command: ["/go/bin/ingress-test"]
        ports:
          - containerPort: 8000

---

kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
      app: auth
  type: NodePort
  ports:
    - port: 9090