USE [users-db];
GO


CREATE TABLE [dbo].[Users](
	[TF] [nchar](7) NOT NULL,
	
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[TF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
